import type { Grade, Template, TemplatePack } from "./types";

const G = (p: Partial<Grade>): Grade => ({
  contrast: 1,
  brightness: 0,
  saturate: 1,
  hue: 0,
  warmth: 0,
  lift: 0,
  gamma: 1,
  ...p,
});

const M = {
  forest: "/media/forest.jpg",
  loft: "/media/loft.jpg",
  night: "/media/street-night.jpg",
  prism: "/media/prism.jpg",
  cafe: "/media/cafe.jpg",
  elif: "/media/portrait-elif.jpg",
  zeynep: "/media/portrait-zeynep.jpg",
  arda: "/media/portrait-arda.jpg",
} as const;

export function gradeCss(g: Grade) {
  const br = Math.max(0.55, 1 + ((g.brightness || 0) + (g.lift || 0) * 0.35) / 80);
  const hue = (g.hue || 0) + (g.warmth || 0) * 0.4;
  const sepia = Math.max(0, Math.min(0.55, (g.warmth || 0) / 70));
  return `brightness(${br}) contrast(${g.contrast || 1}) saturate(${g.saturate || 1}) hue-rotate(${hue}deg) sepia(${sepia})`;
}

function t(
  id: string,
  name: string,
  preview: string,
  pack: TemplatePack,
  grade: Partial<Grade>,
  free = true,
): Template {
  return { id, name, preview, pack, free, grade: G(grade) };
}

function plusPack(): Template[] {
  const out: Template[] = [];
  const add = (
    pack: TemplatePack,
    preview: string,
    rows: [string, string, Partial<Grade>, boolean?][],
  ) => {
    for (const [id, name, grade, free] of rows) out.push(t(id, name, preview, pack, grade, free !== false));
  };
  add("nura", M.elif, [
    ["bp-dogal1", "Doğal 1", { brightness: 10, saturate: 0.94, contrast: 1.06, warmth: 10, lift: 8 }],
    ["bp-dogal2", "Doğal 2", { brightness: 6, saturate: 1.02, contrast: 1.1, warmth: 6, lift: 4 }],
    ["bp-tatli1", "Tatlı 1", { warmth: 26, saturate: 1.22, hue: 10, lift: 12, contrast: 0.94, brightness: 8 }],
    ["bp-tatli2", "Tatlı 2", { warmth: 20, saturate: 1.14, hue: 14, lift: 10, brightness: 10 }],
    ["bp-taze", "Taze", { hue: -10, saturate: 1.18, brightness: 10, contrast: 1.08, warmth: 4 }],
    ["bp-seftali2", "Şeftali 2", { warmth: 28, hue: 12, saturate: 1.1, brightness: 8, lift: 10 }],
    ["bp-gulsuyu2", "Gül suyu 2", { hue: 16, warmth: 18, saturate: 0.9, lift: 14, contrast: 0.92 }],
    ["bp-cam2", "Cam 2", { brightness: 14, saturate: 0.7, contrast: 0.9, lift: 16, warmth: 8 }],
    ["bp-mat2", "Mat 2", { saturate: 0.58, contrast: 1.14, brightness: 2, warmth: 4 }],
    ["bp-inci2", "İnci 2", { brightness: 12, saturate: 0.62, lift: 16, warmth: 6, gamma: 0.9 }],
    ["bp-bal2", "Bal 2", { warmth: 34, saturate: 1.16, contrast: 1.08, gamma: 0.88 }, false],
    ["bp-spa2", "Spa 2", { brightness: 12, saturate: 0.76, contrast: 0.9, lift: 14, warmth: 10 }],
    ["bp-nude2", "Nude 2", { warmth: 16, saturate: 0.84, brightness: 8, contrast: 0.98, lift: 8 }],
    ["bp-pudra2", "Pudra 2", { warmth: 18, saturate: 0.82, lift: 12, hue: 8, contrast: 0.94 }],
    ["bp-kristal2", "Kristal 2", { brightness: 10, saturate: 0.8, contrast: 1.12, warmth: -6, lift: 10 }, false],
    ["bp-saten2", "Saten 2", { saturate: 0.88, contrast: 1.08, warmth: 12, brightness: 6, lift: 6 }],
    ["bp-cilek", "Çilek", { hue: 18, warmth: 20, saturate: 1.2, contrast: 1.06, brightness: 6 }],
    ["bp-lavanta", "Lavanta", { hue: -22, warmth: -6, saturate: 0.88, lift: 12, brightness: 8 }],
    ["bp-mint", "Nane", { hue: -18, saturate: 1.14, brightness: 8, contrast: 1.04, warmth: -2 }],
    ["bp-kakao2", "Kakao 2", { warmth: 18, saturate: 0.7, contrast: 1.1, hue: 8 }],
    ["bp-vanilya2", "Vanilya 2", { warmth: 26, brightness: 10, saturate: 0.9, lift: 10, gamma: 0.92 }],
    ["bp-gumus", "Gümüş", { saturate: 0.45, contrast: 1.16, brightness: 8, warmth: -8, lift: 8 }],
    ["bp-rose2", "Rose 2", { hue: 12, warmth: 14, saturate: 0.86, lift: 12, contrast: 0.94 }],
    ["bp-champagne2", "Şampanya 2", { warmth: 22, lift: 12, contrast: 0.96, saturate: 0.9, brightness: 8 }],
  ]);
  add("orbit", M.zeynep, [
    ["bp-portra", "Portra", { warmth: 18, saturate: 0.92, contrast: 1.08, lift: 6, hue: 4 }],
    ["bp-gold200", "Gold 200", { warmth: 30, saturate: 1.18, contrast: 1.12, hue: 8, gamma: 0.9 }],
    ["bp-fuji400", "Fuji 400", { hue: -8, saturate: 1.16, contrast: 1.1, warmth: 4, brightness: 4 }],
    ["bp-cinestill", "CineStill", { warmth: 22, hue: 16, saturate: 1.2, contrast: 1.14, lift: -4 }, false],
    ["bp-super8b", "Süper 8B", { warmth: 26, saturate: 0.78, contrast: 1.16, lift: 8, hue: 10 }],
    ["bp-chrome", "Chrome", { contrast: 1.28, saturate: 0.62, brightness: 4, warmth: -8 }],
    ["bp-fade", "Soluk film", { saturate: 0.55, contrast: 0.9, brightness: 8, lift: 12, warmth: 10 }],
    ["bp-push2", "Push 2", { contrast: 1.26, saturate: 1.12, brightness: 2, warmth: 6, gamma: 0.92 }],
    ["bp-pull1", "Pull 1", { contrast: 0.92, saturate: 0.84, brightness: 8, lift: 10, warmth: 8 }],
    ["bp-cross2", "Çapraz 2", { hue: 22, saturate: 1.32, contrast: 1.18, warmth: -10 }, false],
    ["bp-lomo2", "Lomo 2", { contrast: 1.3, saturate: 1.28, warmth: 16, lift: -8, hue: 8 }],
    ["bp-teal2", "Cam-köz 2", { hue: -12, warmth: 14, contrast: 1.22, saturate: 1.2 }],
    ["bp-bleach2", "Yıkama 2", { brightness: 14, saturate: 0.58, contrast: 1.12, lift: 12 }],
    ["bp-sepya2", "Sepya 2", { warmth: 36, saturate: 0.42, contrast: 1.14, hue: 16 }],
    ["bp-nb2", "Siyah-beyaz 2", { saturate: 0.05, contrast: 1.3, brightness: 4 }],
    ["bp-nbsoft", "S-B yumuşak", { saturate: 0.08, contrast: 1.08, brightness: 8, lift: 10 }],
  ]);
  add("cehra", M.zeynep, [
    ["bp-editorial2", "Editorial 2", { contrast: 1.22, saturate: 0.88, brightness: 2, warmth: 6 }],
    ["bp-kedi2", "Kedi 2", { contrast: 1.2, saturate: 1.1, warmth: -8, brightness: 2 }],
    ["bp-duman2", "Duman 2", { contrast: 1.24, saturate: 0.7, warmth: -6, brightness: 0 }],
    ["bp-sahne2", "Sahne 2", { contrast: 1.28, warmth: 14, saturate: 1.14, brightness: -4 }, false],
    ["bp-guldudak2", "Gül dudak 2", { hue: 14, warmth: 16, saturate: 1.16, contrast: 1.08 }],
    ["bp-bronz2", "Bronz 2", { warmth: 28, saturate: 1.14, contrast: 1.12, hue: 10 }],
    ["bp-studio2", "Stüdyo 2", { contrast: 1.14, saturate: 0.92, brightness: 8, warmth: 4, lift: 6 }],
    ["bp-noir2", "Noir 2", { saturate: 0.12, contrast: 1.32, brightness: -6 }, false],
    ["bp-inci3", "İnci 3", { brightness: 12, saturate: 0.64, lift: 14, warmth: 4 }],
    ["bp-kadife2", "Kadife 2", { contrast: 1.16, saturate: 0.72, warmth: 12, lift: -4 }],
    ["bp-sicak2", "Sıcak bakış 2", { warmth: 22, saturate: 1.12, contrast: 1.1, brightness: 4 }],
    ["bp-soguk2", "Soğuk bakış 2", { warmth: -18, hue: -12, contrast: 1.18, saturate: 0.9 }],
  ]);
  add("relyn", M.arda, [
    ["bp-arsiv2", "Arşiv 2", { saturate: 0.42, contrast: 1.18, warmth: 12, lift: 8 }],
    ["bp-gazete2", "Gazete 2", { saturate: 0.06, contrast: 1.34, brightness: 2 }],
    ["bp-kart2", "Kart 2", { warmth: 20, saturate: 0.62, contrast: 1.1, lift: 10 }],
    ["bp-hd2", "HD 2", { contrast: 1.26, saturate: 1.12, brightness: 6, gamma: 0.94 }, false],
    ["bp-renk2", "Renk 2", { saturate: 1.34, warmth: 10, contrast: 1.14, brightness: 4 }, false],
    ["bp-toz2", "Toz 2", { saturate: 0.5, contrast: 1.06, warmth: 14, lift: 10 }],
    ["bp-cizik2", "Çizik 2", { contrast: 1.2, saturate: 1.08, brightness: 8 }],
    ["bp-soluk2", "Soluk 2", { saturate: 0.48, brightness: 10, lift: 12, warmth: 16, contrast: 0.94 }],
  ]);
  add("reira", M.loft, [
    ["bp-gunisigi2", "Gün ışığı 2", { warmth: 24, brightness: 10, saturate: 1.08, contrast: 1.06, lift: 6 }],
    ["bp-mavi2", "Mavi saat 2", { warmth: -20, hue: -12, contrast: 1.12, lift: 8 }],
    ["bp-altin3", "Altın 3", { warmth: 34, saturate: 1.16, contrast: 1.1, gamma: 0.9, hue: 8 }, false],
    ["bp-flas2", "Flaş 2", { brightness: 16, contrast: 1.22, saturate: 1.08, warmth: 8 }],
    ["bp-golge2", "Gölge 2", { brightness: -10, contrast: 1.24, saturate: 0.86, lift: -6 }],
    ["bp-pencere3", "Pencere 3", { brightness: 12, warmth: 12, contrast: 0.94, lift: 12 }],
    ["bp-softbox2", "Softbox 2", { brightness: 10, contrast: 1.04, saturate: 0.96, lift: 8 }],
    ["bp-rim2", "Kenar 2", { contrast: 1.22, brightness: -4, saturate: 0.9, warmth: -6 }, false],
  ]);
  add("pacca", M.night, [
    ["bp-neon3", "Neon 3", { hue: 24, saturate: 1.4, contrast: 1.22, warmth: -14 }, false],
    ["bp-vhs2", "VHS 2", { saturate: 0.66, hue: -14, contrast: 1.12, lift: 8 }],
    ["bp-y2k2", "Y2K 2", { hue: 20, saturate: 1.36, contrast: 1.16, warmth: -10, brightness: 4 }],
    ["bp-reel2", "Reel 2", { contrast: 1.28, saturate: 1.2, warmth: 8, brightness: 2 }],
    ["bp-gece2", "Gece 2", { contrast: 1.26, saturate: 1.18, warmth: -12, hue: 8, brightness: -4 }],
    ["bp-pop2", "Pop 2", { saturate: 1.42, contrast: 1.2, hue: 10, brightness: 6 }],
    ["bp-teal3", "Cam-köz 3", { hue: -10, warmth: 16, contrast: 1.24, saturate: 1.22 }, false],
    ["bp-magazine2", "Magazin 2", { contrast: 1.24, saturate: 1.14, brightness: 4, warmth: 8 }],
  ]);
  return out;
}

export const TEMPLATES: Template[] = [
  t("aurora", "Aurora", M.forest, "orbit", { hue: -12, saturate: 1.18, contrast: 1.08, warmth: -8, lift: 6 }),
  t("sitrin", "Sitrin", M.loft, "orbit", { warmth: 22, contrast: 1.1, saturate: 1.12, gamma: 0.95 }),
  t("yörünge", "Yörünge", M.night, "orbit", { hue: 8, warmth: -14, contrast: 1.16, lift: -4, saturate: 0.92 }),
  t("even", "Even", M.prism, "orbit", { saturate: 1.28, contrast: 1.12, warmth: 6, hue: -6 }),
  t("gece", "Gece camı", M.cafe, "orbit", { brightness: -8, contrast: 1.2, warmth: 10, lift: -6, saturate: 0.88 }),
  t("porselen", "Porselen", M.elif, "nura", { brightness: 8, saturate: 0.78, contrast: 0.94, warmth: 8, lift: 10, gamma: 0.92 }),
  t("film", "Analog", M.zeynep, "orbit", { contrast: 1.06, saturate: 0.84, warmth: 14, lift: 4 }),
  t("kuzey", "Kuzey", M.arda, "orbit", { hue: -18, warmth: -16, contrast: 1.14, saturate: 1.1 }, false),
  t("amber", "Amber", M.loft, "orbit", { warmth: 28, saturate: 1.2, contrast: 1.05, gamma: 0.9 }),
  t("sis", "Sis", M.forest, "orbit", { brightness: 6, contrast: 0.88, saturate: 0.7, lift: 14 }),
  t("tungsten", "Tungsten", M.cafe, "orbit", { warmth: 32, hue: 8, contrast: 1.08, saturate: 1.05 }),
  t("buz", "Buz", M.night, "orbit", { warmth: -22, hue: -8, contrast: 1.18, saturate: 0.9, lift: 4 }, false),
  t("zümrüt", "Zümrüt", M.forest, "orbit", { hue: -22, saturate: 1.22, warmth: -4, contrast: 1.07 }),
  t("bakır", "Bakır", M.zeynep, "orbit", { warmth: 18, hue: 12, saturate: 1.08, contrast: 1.04 }),
  t("uzay", "Uzay", M.prism, "orbit", { brightness: -6, contrast: 1.22, saturate: 1.15, hue: -4, warmth: -10 }, false),
  t("gül", "Gül tozu", M.elif, "nura", { warmth: 12, saturate: 0.9, lift: 8, contrast: 0.96 }),
  t("grafit", "Grafit", M.arda, "orbit", { saturate: 0.35, contrast: 1.16, brightness: -4 }),
  t("şafak", "Şafak", M.loft, "orbit", { warmth: 16, hue: -4, brightness: 6, contrast: 1.05, gamma: 0.93 }),
  t("porto", "Porto", M.cafe, "orbit", { warmth: 24, contrast: 1.12, saturate: 0.95, lift: 4 }),
  t("lima", "Lima", M.loft, "orbit", { warmth: 10, brightness: 8, saturate: 1.08, contrast: 0.98 }),
  t("oslo", "Oslo", M.night, "orbit", { warmth: -18, contrast: 1.14, saturate: 0.82, lift: 6 }),
  t("kare-altin", "Kare altın", M.zeynep, "orbit", { warmth: 20, contrast: 1.08, saturate: 1.05, gamma: 0.94 }),
  t("hikaye-tul", "Hikaye tül", M.elif, "orbit", { brightness: 10, contrast: 0.9, saturate: 0.86, lift: 12 }),
  t("reel-koz", "Reel köz", M.cafe, "orbit", { warmth: 26, contrast: 1.18, saturate: 1.14, hue: 6 }),
  t("cover-ink", "Cover mürekkep", M.arda, "orbit", { saturate: 0.4, contrast: 1.22, brightness: -6, warmth: -8 }),
  t("soft-grid", "Soft grid", M.loft, "orbit", { brightness: 6, saturate: 0.92, contrast: 0.96, warmth: 8 }),
  t("glow-reel", "Glow reel", M.prism, "orbit", { brightness: 8, saturate: 1.2, contrast: 1.1, warmth: 4, lift: 8 }, false),
  t("dew", "Dew", M.elif, "nura", { brightness: 10, saturate: 0.88, contrast: 0.92, lift: 12, warmth: 10 }),
  t("ipek", "İpek", M.zeynep, "nura", { saturate: 0.82, contrast: 0.94, warmth: 12, gamma: 0.92, lift: 8 }),
  t("pudra", "Pudra", M.elif, "nura", { warmth: 14, saturate: 0.9, brightness: 6, contrast: 0.95 }),
  t("vanilya", "Vanilya", M.loft, "nura", { warmth: 22, brightness: 8, saturate: 0.96, gamma: 0.93 }),
  t("sampanya-ten", "Şampanya ten", M.zeynep, "nura", { warmth: 18, lift: 10, contrast: 0.97, saturate: 0.94 }),
  t("mat-ipek", "Mat ipek", M.elif, "nura", { saturate: 0.72, contrast: 1.04, brightness: 2, warmth: 6 }),
  t("gul-sut", "Gül süt", M.zeynep, "nura", { warmth: 16, hue: 8, saturate: 0.86, lift: 10 }),
  t("bal-ozu", "Bal özü", M.cafe, "nura", { warmth: 28, saturate: 1.1, contrast: 1.06, gamma: 0.9 }, false),
  t("cehre-acik", "Çehre açık", M.elif, "cehra", { brightness: 8, contrast: 1.04, saturate: 1.02, lift: 6 }),
  t("bakis-look", "Bakış", M.zeynep, "cehra", { contrast: 1.12, saturate: 1.08, warmth: -4, brightness: 4 }),
  t("sahnede", "Sahnede", M.arda, "cehra", { contrast: 1.18, warmth: 8, saturate: 1.1, brightness: -2 }),
  t("kadife-look", "Kadife", M.zeynep, "cehra", { contrast: 1.08, saturate: 0.8, warmth: 10, lift: -4 }),
  t("inci-look", "İnci", M.elif, "cehra", { brightness: 10, saturate: 0.7, warmth: 4, lift: 12, gamma: 0.92 }),
  t("gece-look", "Gece look", M.night, "cehra", { brightness: -6, contrast: 1.2, saturate: 0.95, warmth: -8 }, false),
  t("arsiv", "Arşiv", M.arda, "relyn", { saturate: 0.55, contrast: 1.1, warmth: 8, lift: 6 }),
  t("soluk-kart", "Soluk kart", M.loft, "relyn", { contrast: 0.9, saturate: 0.62, brightness: 6, lift: 10, warmth: 12 }),
  t("gazete", "Gazete", M.arda, "relyn", { saturate: 0.12, contrast: 1.24, brightness: 2 }),
  t("cam-net", "Cam net", M.zeynep, "relyn", { contrast: 1.16, saturate: 1.06, brightness: 4, gamma: 0.96 }),
  t("dortk-iz", "Net iz", M.prism, "relyn", { contrast: 1.2, saturate: 1.12, brightness: 6, warmth: 4 }),
  t("eski-renk", "Eski renk", M.cafe, "relyn", { warmth: 18, saturate: 1.15, contrast: 1.08, hue: 8, lift: 4 }, false),
  t("studio-01", "Stüdyo 01", M.prism, "reira", { contrast: 1.1, saturate: 0.96, brightness: 4, warmth: 2 }),
  t("pencere-tpl", "Pencere", M.loft, "reira", { brightness: 8, warmth: 8, contrast: 0.98, lift: 8 }),
  t("sokak-fener", "Sokak feneri", M.night, "reira", { warmth: 10, contrast: 1.04, brightness: 0, saturate: 0.96 }),
  t("altin-saat", "Altın saat", M.cafe, "reira", { warmth: 12, saturate: 1.04, contrast: 1.03, gamma: 0.97 }),
  t("mavi-saat", "Mavi saat", M.night, "reira", { warmth: -8, hue: -4, contrast: 1.04, lift: 3 }),
  t("loft-ampul", "Loft ampul", M.loft, "reira", { warmth: 12, hue: 4, contrast: 1.03, saturate: 1.02 }, false),
  t("kirik-cam", "Kırık cam", M.prism, "pacca", { contrast: 1.08, saturate: 1.06, hue: -3, brightness: 1 }),
  t("yavas-perde", "Yavaş perde", M.forest, "pacca", { contrast: 0.96, saturate: 0.92, brightness: 4, lift: 4, warmth: 3 }),
  t("neon-iz", "Neon iz", M.night, "pacca", { hue: 6, saturate: 1.1, contrast: 1.05, warmth: -4 }),
  t("punch-tpl", "Punch", M.arda, "pacca", { contrast: 1.08, saturate: 1.05, brightness: 1, warmth: 2 }),
  t("soft-cut", "Soft cut", M.elif, "pacca", { contrast: 0.94, saturate: 0.9, brightness: 6, lift: 8 }),
  t("serit-3", "Şerit 3", M.loft, "pacca", { contrast: 1.1, saturate: 1.08, hue: -6, warmth: 8 }),
  t("titrek", "Titrek", M.prism, "pacca", { contrast: 1.22, saturate: 1.2, hue: 12, brightness: -2 }),
  t("film-yanigi", "Film yanığı", M.cafe, "pacca", { warmth: 12, contrast: 1.05, saturate: 1.03, lift: -2, hue: 3 }),
  t("kaset-sis", "Kaset sis", M.forest, "pacca", { saturate: 0.55, contrast: 0.92, brightness: 4, lift: 8, hue: -6 }, false),
  t("matcha", "Matcha", M.forest, "orbit", { hue: -20, saturate: 1.1, warmth: -6, contrast: 1.04 }),
  t("kil", "Kil", M.loft, "orbit", { warmth: 16, saturate: 0.78, contrast: 1.02, lift: 6 }),
  t("keten", "Keten", M.elif, "orbit", { saturate: 0.7, contrast: 0.96, warmth: 10, brightness: 4 }),
  t("bal", "Bal", M.cafe, "orbit", { warmth: 26, saturate: 1.16, contrast: 1.04, gamma: 0.93 }),
  t("nar", "Nar", M.zeynep, "nura", { hue: 12, warmth: 14, saturate: 1.12, contrast: 1.06 }),
  t("zeytin", "Zeytin", M.forest, "nura", { hue: -16, warmth: -4, saturate: 0.92, contrast: 1.05 }),
  t("kar", "Kar", M.prism, "nura", { brightness: 12, saturate: 0.65, contrast: 0.92, warmth: -8, lift: 14 }),
  t("incir", "İncir", M.cafe, "nura", { warmth: 12, hue: 6, saturate: 0.88, contrast: 1.02 }),

  t("kale", "Kale", M.night, "orbit", { contrast: 1.06, saturate: 1.05, warmth: -3, brightness: 2, hue: -1 }),
  t("krema", "Krema", M.loft, "orbit", { warmth: 18, saturate: 0.78, contrast: 0.96, lift: 8, gamma: 0.94 }),
  t("tarla", "Tarla", M.forest, "orbit", { brightness: 10, saturate: 0.86, hue: -10, contrast: 0.98, lift: 6 }),
  t("col", "Çöl", M.cafe, "orbit", { warmth: 20, saturate: 0.7, contrast: 1.04, lift: 8, hue: 8 }),
  t("mercan", "Mercan", M.zeynep, "orbit", { warmth: 22, saturate: 1.16, hue: 10, contrast: 1.08, gamma: 0.94 }),
  t("uyku", "Uyku", M.elif, "orbit", { saturate: 0.62, warmth: 12, contrast: 0.9, brightness: 4, lift: 10 }),
  t("salon", "Salon", M.loft, "orbit", { warmth: 16, brightness: 8, contrast: 1.04, saturate: 1.06, lift: 6 }),
  t("portakal", "Portakal", M.cafe, "orbit", { warmth: 28, hue: 14, saturate: 1.12, contrast: 1.06 }),
  t("capraz", "Çapraz", M.arda, "orbit", { contrast: 1.28, saturate: 1.2, warmth: 8, brightness: -4, gamma: 0.9 }),
  t("plaka", "Plaka", M.zeynep, "orbit", { warmth: 24, saturate: 0.72, contrast: 1.1, lift: 8, hue: 6 }),
  t("dogus", "Doğuş", M.loft, "orbit", { brightness: 12, warmth: 14, saturate: 0.88, contrast: 0.96, lift: 8 }),
  t("iskele", "İskele", M.night, "orbit", { warmth: -10, hue: -12, contrast: 1.18, saturate: 0.9, brightness: 2 }),
  t("dag", "Dağ", M.forest, "orbit", { warmth: 10, saturate: 0.8, contrast: 1.08, lift: 4, hue: -6 }),
  t("sogut", "Söğüt", M.forest, "orbit", { saturate: 0.28, hue: -16, contrast: 1.12, brightness: 4, lift: 6 }),
  t("yetmis", "Yetmiş", M.cafe, "orbit", { hue: 18, warmth: 8, saturate: 1.22, contrast: 1.1, brightness: 4 }),
  t("bronz", "Bronz", M.zeynep, "orbit", { warmth: 22, contrast: 1.16, saturate: 0.92, hue: 8, gamma: 0.93 }),
  t("kus", "Kuş", M.loft, "orbit", { warmth: 20, saturate: 0.74, contrast: 1.02, lift: 10 }),
  t("tunel", "Tünel", M.night, "orbit", { brightness: -10, contrast: 1.24, saturate: 0.85, warmth: 12, lift: -8 }),
  t("kizartma", "Kızartma", M.cafe, "orbit", { warmth: 36, hue: 10, contrast: 1.18, saturate: 1.08, brightness: 2 }),
  t("orman-evi", "Orman evi", M.forest, "orbit", { hue: -14, warmth: 8, saturate: 0.82, contrast: 0.96, lift: 8 }),
  t("sahil", "Sahil", M.elif, "orbit", { brightness: 8, saturate: 0.76, warmth: 6, contrast: 0.94, lift: 10 }),
  t("aksam-cani", "Akşam çanı", M.night, "orbit", { warmth: 14, contrast: 1.12, saturate: 0.88, brightness: -4, lift: 4 }),
  t("flas", "Flaş", M.prism, "orbit", { brightness: 14, contrast: 1.2, saturate: 1.16, warmth: 8, gamma: 0.92 }),
  t("ham", "Ham", M.arda, "orbit", { contrast: 1.08, saturate: 1.04, brightness: 2, warmth: 2 }),
  t("loft-lofi", "Loft lofi", M.loft, "orbit", { contrast: 1.22, saturate: 1.24, warmth: 10, hue: 6, brightness: -2 }),
  t("cam-ludwig", "Cam", M.elif, "orbit", { contrast: 1.14, saturate: 0.92, brightness: 6, warmth: 4, gamma: 0.96 }),
  t("pembe-toz", "Pembe toz", M.zeynep, "orbit", { hue: 10, warmth: 12, saturate: 0.84, lift: 10, contrast: 0.96 }),
  t("yesil-bahce", "Yeşil bahçe", M.forest, "orbit", { hue: -18, saturate: 0.9, contrast: 1.04, brightness: 6, lift: 6 }),
  t("ay-isigi", "Ay ışığı", M.night, "orbit", { saturate: 0.22, contrast: 1.1, brightness: 4, warmth: -8, lift: 8 }),
  t("kareli", "Kareli", M.elif, "orbit", { saturate: 0.55, contrast: 0.94, brightness: 8, warmth: 6, lift: 8 }),
  t("musk", "Misk", M.zeynep, "orbit", { warmth: 14, saturate: 0.8, contrast: 1.06, hue: 6, lift: 4 }),
  t("linen-story", "Keten hikaye", M.loft, "orbit", { saturate: 0.68, warmth: 12, brightness: 8, contrast: 0.95, lift: 8 }),
  t("dusk-grid", "Alacakaranlık", M.night, "orbit", { warmth: 8, contrast: 1.16, saturate: 0.9, brightness: -4, hue: -6 }),
  t("noon", "Öğle", M.elif, "orbit", { brightness: 10, contrast: 1.06, saturate: 1.08, warmth: 8, gamma: 0.97 }),
  t("velvet-post", "Kadife gönderi", M.zeynep, "orbit", { contrast: 1.12, saturate: 0.76, warmth: 10, lift: -2 }),
  t("clay-reel", "Kil reel", M.cafe, "orbit", { warmth: 18, saturate: 0.82, contrast: 1.04, hue: 8, lift: 6 }),
  t("paper", "Kağıt", M.arda, "orbit", { saturate: 0.48, contrast: 1.08, brightness: 6, warmth: 8, lift: 8 }),
  t("chrome-ig", "Krom", M.prism, "orbit", { contrast: 1.2, saturate: 0.7, brightness: 4, warmth: -6, gamma: 0.95 }),
  t("sage", "Adaçayı", M.forest, "orbit", { hue: -14, saturate: 0.86, warmth: -2, contrast: 1.02, lift: 6 }),
  t("rust", "Pas", M.cafe, "orbit", { warmth: 24, hue: 12, saturate: 0.94, contrast: 1.1, brightness: -2 }),
  t("bone", "Kemik", M.elif, "orbit", { saturate: 0.52, warmth: 10, brightness: 8, contrast: 0.96, lift: 10 }),
  t("ink-wash", "Mürekkep yıkama", M.arda, "orbit", { saturate: 0.18, contrast: 1.18, brightness: -2, warmth: -4 }),

  t("cam-ten", "Cam ten", M.elif, "nura", { brightness: 10, saturate: 0.74, contrast: 0.93, lift: 12, warmth: 8 }),
  t("sut", "Süt", M.zeynep, "nura", { brightness: 12, saturate: 0.68, contrast: 0.9, warmth: 10, lift: 14, gamma: 0.92 }),
  t("balsam", "Balsam", M.elif, "nura", { warmth: 16, saturate: 0.92, contrast: 0.98, lift: 8, brightness: 6 }),
  t("gloss", "Gloss", M.zeynep, "nura", { brightness: 8, saturate: 1.08, contrast: 1.04, warmth: 10, lift: 6 }),
  t("satin", "Saten", M.elif, "nura", { saturate: 0.84, contrast: 1.02, warmth: 8, brightness: 4, gamma: 0.95 }),
  t("mat-ten", "Mat ten", M.zeynep, "nura", { saturate: 0.66, contrast: 1.08, brightness: 2, warmth: 4 }),
  t("seftali", "Şeftali", M.elif, "nura", { warmth: 18, hue: 8, saturate: 0.96, brightness: 8, lift: 8 }),
  t("fildisi", "Fildişi", M.zeynep, "nura", { brightness: 10, saturate: 0.7, warmth: 6, contrast: 0.94, lift: 12 }),
  t("opal", "Opal", M.prism, "nura", { brightness: 8, saturate: 0.78, warmth: -4, lift: 10, hue: -6 }),
  t("sabah-nur", "Sabah nur", M.loft, "nura", { brightness: 12, warmth: 14, saturate: 0.9, contrast: 0.96, lift: 8 }),
  t("spa", "Spa", M.elif, "nura", { brightness: 8, saturate: 0.8, contrast: 0.92, warmth: 8, lift: 10, gamma: 0.93 }),
  t("kizil-isirti", "Kızıl ışıltı", M.zeynep, "nura", { warmth: 20, hue: 10, saturate: 1.1, contrast: 1.04, brightness: 4 }, false),
  t("limon-cicek", "Limon çiçek", M.forest, "nura", { hue: -8, warmth: 10, saturate: 0.94, brightness: 8, lift: 6 }),
  t("gul-cam", "Gül cam", M.elif, "nura", { hue: 8, warmth: 12, saturate: 0.86, lift: 10, contrast: 0.96 }),
  t("cay-sut", "Çay süt", M.cafe, "nura", { warmth: 20, saturate: 0.82, contrast: 0.98, lift: 8, brightness: 6 }),
  t("pamuk", "Pamuk", M.elif, "nura", { brightness: 12, saturate: 0.72, contrast: 0.9, warmth: 8, lift: 12 }),
  t("gul-suyu", "Gül suyu", M.zeynep, "nura", { hue: 10, warmth: 14, saturate: 0.88, lift: 10, contrast: 0.95 }),
  t("ipek-gece", "İpek gece", M.night, "nura", { brightness: 4, saturate: 0.78, contrast: 1.08, warmth: 6, lift: 6 }, false),
  t("seftali-sis", "Şeftali sis", M.elif, "nura", { warmth: 16, brightness: 10, saturate: 0.84, contrast: 0.92, lift: 12 }),
  t("fildisi-parilti", "Fildişi parıltı", M.zeynep, "nura", { brightness: 10, saturate: 0.76, warmth: 8, lift: 10, gamma: 0.93 }),
  t("bal-cigi", "Bal çiği", M.cafe, "nura", { warmth: 24, saturate: 1.06, contrast: 1.02, lift: 8, gamma: 0.92 }),
  t("mika", "Mika", M.prism, "nura", { brightness: 8, saturate: 0.9, contrast: 1.06, warmth: 2, lift: 8 }),
  t("nude-ten", "Nude ten", M.elif, "nura", { warmth: 12, saturate: 0.86, contrast: 0.97, brightness: 6, lift: 8 }),
  t("inceli", "İnceli", M.zeynep, "nura", { saturate: 0.7, contrast: 1.02, warmth: 6, brightness: 4, lift: 6 }),

  t("editorial", "Editorial", M.zeynep, "cehra", { contrast: 1.16, saturate: 0.92, brightness: 2, warmth: 4 }),
  t("acik-gulumse", "Açık gülümse", M.elif, "cehra", { brightness: 10, contrast: 1.02, saturate: 1.04, warmth: 8, lift: 8 }),
  t("kirpik-look", "Kirpik look", M.zeynep, "cehra", { contrast: 1.1, saturate: 1.06, brightness: 2, warmth: -2 }),
  t("kas-look", "Kaş look", M.arda, "cehra", { contrast: 1.12, saturate: 0.96, brightness: 2, warmth: 2 }),
  t("sahne-isik", "Sahne ışık", M.night, "cehra", { contrast: 1.2, warmth: 10, saturate: 1.08, brightness: -2 }),
  t("kontur-look", "Kontür look", M.zeynep, "cehra", { contrast: 1.14, saturate: 0.84, warmth: 8, lift: -4 }),
  t("ten-parlak", "Ten parlak", M.elif, "cehra", { brightness: 8, saturate: 1.02, contrast: 1.04, warmth: 8, lift: 6 }),
  t("soguk-bakis", "Soğuk bakış", M.arda, "cehra", { warmth: -12, contrast: 1.14, saturate: 0.94, hue: -8, brightness: 4 }),
  t("sicak-bakis", "Sıcak bakış", M.zeynep, "cehra", { warmth: 16, contrast: 1.08, saturate: 1.06, brightness: 4 }),
  t("noir-cehre", "Noir çehre", M.arda, "cehra", { saturate: 0.2, contrast: 1.22, brightness: -4 }, false),
  t("gul-dudak", "Gül dudak", M.elif, "cehra", { hue: 10, warmth: 12, saturate: 1.08, contrast: 1.04, brightness: 4 }),
  t("duman-goz", "Duman göz", M.zeynep, "cehra", { contrast: 1.16, saturate: 0.78, warmth: -4, brightness: 2 }),
  t("bronz-cehre", "Bronz çehre", M.zeynep, "cehra", { warmth: 20, saturate: 1.08, contrast: 1.08, hue: 8 }),
  t("studio-face", "Stüdyo çehre", M.elif, "cehra", { contrast: 1.08, saturate: 0.96, brightness: 6, warmth: 4, lift: 4 }),
  t("soft-smile", "Yumuşak gülümse", M.elif, "cehra", { brightness: 8, saturate: 0.94, contrast: 0.98, warmth: 10, lift: 8 }),
  t("kedi-goz", "Kedi göz", M.zeynep, "cehra", { contrast: 1.14, saturate: 1.04, warmth: -6, brightness: 2 }),
  t("mercan-cehre", "Mercan çehre", M.elif, "cehra", { warmth: 18, hue: 10, saturate: 1.1, contrast: 1.06 }),
  t("sarap-cehre", "Şarap çehre", M.zeynep, "cehra", { hue: 12, warmth: 8, saturate: 0.9, contrast: 1.12, brightness: -2 }, false),
  t("gunes-cehre", "Güneş çehre", M.loft, "cehra", { warmth: 22, brightness: 8, saturate: 1.06, contrast: 1.04, lift: 6 }),
  t("buz-cehre", "Buz çehre", M.prism, "cehra", { warmth: -14, hue: -8, contrast: 1.12, saturate: 0.88, lift: 8 }),

  t("tarama", "Tarama", M.arda, "relyn", { saturate: 0.4, contrast: 1.18, brightness: 4, warmth: 6 }),
  t("polaroid-onar", "Kart onar", M.loft, "relyn", { warmth: 14, saturate: 0.7, contrast: 1.06, lift: 8, brightness: 6 }),
  t("soluk-renk", "Soluk renk", M.cafe, "relyn", { saturate: 0.5, warmth: 16, contrast: 0.96, lift: 10, brightness: 6 }),
  t("eski-isik", "Eski ışık", M.loft, "relyn", { warmth: 20, contrast: 1.1, saturate: 1.08, hue: 6, gamma: 0.94 }),
  t("cizik", "Çizik sil", M.arda, "relyn", { contrast: 1.14, saturate: 1.04, brightness: 6, gamma: 0.96 }),
  t("toz-tarama", "Toz tarama", M.cafe, "relyn", { saturate: 0.58, contrast: 1.08, warmth: 10, lift: 8, brightness: 4 }),
  t("baski-net", "Baskı net", M.zeynep, "relyn", { contrast: 1.22, saturate: 1.1, brightness: 4, warmth: 4 }),
  t("kaset-kare", "Kaset kare", M.night, "relyn", { saturate: 0.62, contrast: 1.12, hue: -8, warmth: -4, brightness: 2 }),
  t("soluk-mavi", "Soluk mavi", M.prism, "relyn", { hue: -12, warmth: -10, saturate: 0.7, contrast: 1.08, lift: 8 }),
  t("sepya-kart", "Sepya kart", M.cafe, "relyn", { warmth: 28, saturate: 0.55, contrast: 1.1, hue: 12, lift: 6 }),
  t("gren-duzelt", "Gren düzelt", M.arda, "relyn", { contrast: 1.16, saturate: 1.08, brightness: 4, gamma: 0.97 }),
  t("cam-onar", "Cam onar", M.zeynep, "relyn", { contrast: 1.18, saturate: 1.1, brightness: 6, warmth: 2, gamma: 0.96 }),
  t("gece-duzelt", "Gece düzelt", M.night, "relyn", { contrast: 1.2, brightness: 8, saturate: 1.06, warmth: 4, lift: 4 }),
  t("portre-onar", "Portre onar", M.elif, "relyn", { contrast: 1.12, saturate: 1.08, brightness: 6, warmth: 8, lift: 6 }),
  t("kagit-onar", "Kağıt onar", M.loft, "relyn", { saturate: 0.66, contrast: 1.08, warmth: 10, brightness: 8, lift: 8 }),
  t("analog-onar", "Analog onar", M.cafe, "relyn", { warmth: 16, saturate: 0.88, contrast: 1.1, lift: 6, hue: 6 }, false),
  t("siyah-beyaz-hd", "Siyah-beyaz HD", M.arda, "relyn", { saturate: 0.08, contrast: 1.26, brightness: 4 }),
  t("renk-cagir", "Renk çağır", M.zeynep, "relyn", { saturate: 1.22, warmth: 12, contrast: 1.1, brightness: 4, hue: 4 }, false),

  t("bounce-isik", "Yansıyan ışık", M.elif, "reira", { brightness: 10, contrast: 0.98, saturate: 0.96, lift: 10, warmth: 6 }),
  t("tavan", "Tavan ışık", M.loft, "reira", { brightness: 6, contrast: 1.08, saturate: 0.94, warmth: 4, lift: 4 }),
  t("pencere-2", "Pencere 02", M.loft, "reira", { brightness: 10, warmth: 10, contrast: 0.96, lift: 10 }),
  t("softbox", "Yumuşak kutu", M.elif, "reira", { brightness: 8, contrast: 1.02, saturate: 0.98, warmth: 4, lift: 6 }),
  t("rim-pro", "Kenar pro", M.arda, "reira", { contrast: 1.16, brightness: -2, saturate: 0.94, warmth: -4, lift: -2 }, false),
  t("gun-batimi", "Gün batımı", M.cafe, "reira", { warmth: 32, saturate: 1.14, contrast: 1.08, gamma: 0.92, hue: 8 }),
  t("mavi-pencere", "Mavi pencere", M.night, "reira", { warmth: -16, hue: -10, contrast: 1.08, lift: 8, brightness: 4 }),
  t("kafe-masa", "Kafe masa", M.cafe, "reira", { warmth: 24, hue: 8, contrast: 1.06, saturate: 1.02, brightness: 2 }),
  t("gece-dis", "Gece dış", M.night, "reira", { brightness: -4, contrast: 1.18, saturate: 0.92, warmth: 6, lift: -2 }),
  t("studio-02", "Stüdyo 02", M.prism, "reira", { contrast: 1.12, saturate: 0.94, brightness: 6, warmth: 0, lift: 4 }),
  t("studio-03", "Stüdyo 03", M.elif, "reira", { contrast: 1.06, saturate: 1.02, brightness: 8, warmth: 6, lift: 6 }),
  t("yagmur-cam", "Yağmur cam", M.night, "reira", { warmth: -8, contrast: 1.14, saturate: 0.86, brightness: 2, lift: 6 }),
  t("altin-2", "Altın 02", M.cafe, "reira", { warmth: 28, saturate: 1.1, contrast: 1.04, gamma: 0.93, brightness: 4 }),
  t("tungsten-2", "Tungsten 02", M.loft, "reira", { warmth: 30, hue: 10, contrast: 1.08, saturate: 1.04 }),
  t("kapali-gokyuzu", "Kapalı gökyüzü", M.forest, "reira", { brightness: 6, saturate: 0.78, contrast: 0.96, warmth: -4, lift: 8 }),
  t("flas-cek", "Flaş çek", M.elif, "reira", { brightness: 12, contrast: 1.14, saturate: 1.04, warmth: 6, gamma: 0.95 }),
  t("gölge-cek", "Gölge çek", M.arda, "reira", { brightness: -6, contrast: 1.16, saturate: 0.9, warmth: 2, lift: -4 }),
  t("ikinci-deneme", "İkinci deneme", M.zeynep, "reira", { contrast: 1.08, saturate: 1.02, brightness: 6, warmth: 8, lift: 6 }),

  t("hook-kare", "Hook kare", M.arda, "pacca", { contrast: 1.24, saturate: 1.16, brightness: 2, warmth: 4 }),
  t("dump-bej", "Dump bej", M.loft, "pacca", { warmth: 14, saturate: 0.72, contrast: 0.96, brightness: 6, lift: 8 }),
  t("dump-gece", "Dump gece", M.night, "pacca", { brightness: -6, contrast: 1.18, saturate: 0.88, warmth: -6, hue: -4 }),
  t("dump-altin", "Dump altın", M.cafe, "pacca", { warmth: 26, contrast: 1.12, saturate: 1.1, hue: 6 }),
  t("y2k-cam", "Y2K cam", M.prism, "pacca", { hue: 16, saturate: 1.28, contrast: 1.14, brightness: 4, warmth: -8 }),
  t("eski-servet", "Eski servet", M.loft, "pacca", { saturate: 0.62, warmth: 12, contrast: 1.08, brightness: 2, lift: 4 }),
  t("temiz-kiz", "Temiz kare", M.elif, "pacca", { brightness: 10, saturate: 0.88, contrast: 0.96, warmth: 8, lift: 10 }),
  t("koyu-feminen", "Koyu kadife", M.zeynep, "pacca", { brightness: -4, contrast: 1.16, saturate: 0.82, warmth: 8, lift: -2 }, false),
  t("estetik-dokum", "Estetik döküm", M.elif, "pacca", { saturate: 0.74, contrast: 0.94, brightness: 8, warmth: 10, lift: 10 }),
  t("slow-reveal", "Yavaş açılış", M.forest, "pacca", { contrast: 0.9, saturate: 0.8, brightness: 8, lift: 10, warmth: 4 }),
  t("zoom-vurus", "Zoom vuruş", M.arda, "pacca", { contrast: 1.26, saturate: 1.12, brightness: 0, warmth: 2 }),
  t("vhs-kaset", "VHS kaset", M.night, "pacca", { saturate: 0.7, hue: -10, contrast: 1.08, brightness: 2, lift: 6 }),
  t("sinema-serif", "Sinema şerit", M.arda, "pacca", { contrast: 1.18, saturate: 0.86, warmth: 8, brightness: -2, lift: -2 }),
  t("renk-pop", "Renk pop", M.prism, "pacca", { saturate: 1.36, contrast: 1.16, hue: 8, brightness: 4 }),
  t("ikili-kesim", "İkili kesim", M.zeynep, "pacca", { contrast: 1.12, saturate: 1.04, warmth: 4, brightness: 2 }),
  t("polaroid-yigin", "Kart yığın", M.loft, "pacca", { warmth: 16, saturate: 0.78, contrast: 1.04, lift: 8, brightness: 4 }),
  t("yazi-kinetik", "Yazı kinetik", M.elif, "pacca", { contrast: 1.14, saturate: 1.08, brightness: 6, warmth: 2 }),
  t("gece-sehir", "Gece şehir", M.night, "pacca", { hue: 8, contrast: 1.2, saturate: 1.14, warmth: -8, brightness: -2 }),
  t("altin-reel", "Altın reel", M.cafe, "pacca", { warmth: 28, saturate: 1.16, contrast: 1.12, hue: 6, gamma: 0.93 }),
  t("matcha-klip", "Matcha klip", M.forest, "pacca", { hue: -18, saturate: 1.12, contrast: 1.06, warmth: -4 }),
  t("bej-hikaye", "Bej hikaye", M.loft, "pacca", { warmth: 14, saturate: 0.7, contrast: 0.94, brightness: 8, lift: 10 }),
  t("koyu-akademi", "Koyu akademi", M.arda, "pacca", { saturate: 0.5, contrast: 1.16, warmth: 6, brightness: -4 }),
  t("pastel-hikaye", "Pastel hikaye", M.elif, "pacca", { brightness: 12, saturate: 0.76, contrast: 0.9, warmth: 10, lift: 12 }),
  t("neon-gece", "Neon gece", M.night, "pacca", { hue: 20, saturate: 1.34, contrast: 1.18, warmth: -12 }, false),
  t("film-burn-2", "Film yanık 02", M.cafe, "pacca", { warmth: 32, contrast: 1.16, saturate: 1.06, lift: -8, hue: 10 }),
  t("beat-gorsel", "Vuruş görsel", M.arda, "pacca", { contrast: 1.3, saturate: 1.18, brightness: 2, warmth: 4 }),
  t("gradient-tul", "Gradyan tül", M.elif, "pacca", { brightness: 8, saturate: 0.86, contrast: 0.92, lift: 12, hue: 6 }),
  t("letterbox-look", "Şerit kare", M.arda, "pacca", { contrast: 1.14, saturate: 0.9, brightness: -2, warmth: 4 }),
  t("soft-dump", "Yumuşak dump", M.elif, "pacca", { brightness: 10, saturate: 0.82, contrast: 0.94, warmth: 8, lift: 10 }),
  t("grain-story", "Gren hikaye", M.loft, "pacca", { saturate: 0.72, contrast: 1.06, warmth: 10, lift: 6, brightness: 4 }),
  t("chrome-reel", "Krom reel", M.prism, "pacca", { contrast: 1.22, saturate: 0.68, brightness: 4, warmth: -8 }),
  t("cyan-night", "Camgöbeği gece", M.night, "pacca", { hue: -16, warmth: -14, saturate: 1.12, contrast: 1.16, brightness: 2 }),
  t("warm-dump", "Sıcak dump", M.cafe, "pacca", { warmth: 22, saturate: 0.92, contrast: 1.04, brightness: 6, lift: 6 }),
  t("cool-dump", "Soğuk dump", M.forest, "pacca", { warmth: -12, hue: -10, saturate: 0.86, contrast: 1.06, lift: 6 }),
  t("magazine", "Magazin", M.zeynep, "pacca", { contrast: 1.18, saturate: 1.08, brightness: 4, warmth: 6 }),
  t("kapak-art", "Kapak art", M.arda, "pacca", { contrast: 1.22, saturate: 1.12, brightness: 0, warmth: 2, hue: -4 }),
  t("thumbnail", "Küçük kare", M.elif, "pacca", { contrast: 1.16, saturate: 1.14, brightness: 6, warmth: 6 }),
  t("hook-frame", "Hook çerçeve", M.arda, "pacca", { contrast: 1.28, saturate: 1.1, brightness: 2, warmth: 0 }),
  t("speed-ramp", "Hız rampası", M.night, "pacca", { contrast: 1.2, saturate: 1.16, hue: 8, brightness: 2 }),
  t("split-glow", "Bölünmüş ışıltı", M.prism, "pacca", { brightness: 8, saturate: 1.18, contrast: 1.1, warmth: 4, lift: 6 }),
  t("freeze", "Donuk kare", M.zeynep, "pacca", { contrast: 1.12, saturate: 0.9, brightness: 4, warmth: -4, lift: 4 }),
  t("flash-cut", "Flaş kesim", M.elif, "pacca", { brightness: 12, contrast: 1.18, saturate: 1.08, warmth: 8 }),
  t("analog-roll", "Analog rulo", M.cafe, "pacca", { warmth: 18, saturate: 0.8, contrast: 1.08, lift: 6, hue: 6 }),
  t("teal-orange", "Cam & köz", M.night, "pacca", { hue: -8, warmth: 10, contrast: 1.18, saturate: 1.14, brightness: 0 }),
  t("bleach", "Açık yıkama", M.elif, "pacca", { brightness: 12, saturate: 0.7, contrast: 1.08, lift: 10, warmth: 4 }),
  t("skip-bleach", "Atlanmış yıkama", M.arda, "pacca", { contrast: 1.2, saturate: 0.62, brightness: 4, warmth: 6 }, false),
  t("cross-process", "Çapraz banyo", M.prism, "pacca", { hue: 14, saturate: 1.26, contrast: 1.16, warmth: -6 }),
  t("lomo", "Lomo", M.cafe, "pacca", { contrast: 1.22, saturate: 1.2, warmth: 12, lift: -6, hue: 6 }),
  t("super8", "Süper 8", M.loft, "pacca", { warmth: 22, saturate: 0.84, contrast: 1.08, lift: 6, hue: 8 }),
  t("16mm", "16 mm", M.forest, "pacca", { saturate: 0.78, contrast: 1.1, warmth: 10, lift: 4, brightness: 2 }),
  t("35mm-push", "35 mm itiş", M.arda, "pacca", { contrast: 1.18, saturate: 1.06, warmth: 8, brightness: 2, gamma: 0.95 }),
  t("night-drive", "Gece sürüş", M.night, "pacca", { hue: 10, contrast: 1.22, saturate: 1.18, warmth: -10, brightness: -4 }),
  t("yagmur-reel", "Yağmur reel", M.night, "pacca", { warmth: -8, contrast: 1.12, saturate: 0.88, brightness: 2, lift: 6 }),
  t("catı", "Çatı", M.night, "pacca", { contrast: 1.16, saturate: 1.04, warmth: 4, brightness: -2 }),
  t("metro", "Metro", M.night, "pacca", { hue: 6, contrast: 1.18, saturate: 1.08, warmth: -4, brightness: 0 }),
  t("bogaz", "Boğaz", M.night, "pacca", { hue: -8, warmth: -6, contrast: 1.12, saturate: 1.06, brightness: 4 }),
  t("istanbul-night", "İstanbul gece", M.night, "pacca", { warmth: 8, contrast: 1.2, saturate: 1.12, hue: 4, brightness: -2 }),
  t("ege", "Ege", M.forest, "pacca", { hue: -12, warmth: 10, saturate: 1.08, contrast: 1.04, brightness: 6 }),
  t("kapadokya", "Kapadokya", M.cafe, "pacca", { warmth: 24, saturate: 0.9, contrast: 1.08, hue: 8, lift: 6 }),
  t("karadeniz", "Karadeniz", M.forest, "pacca", { hue: -16, saturate: 1.1, contrast: 1.08, warmth: -2, brightness: 2 }),
  ...plusPack(),
];
